import java.util.Scanner;
import java.util.ArrayList;
public class Teste{
    public static void main (String[] args){
        public Scanner e = new Scanner(System.in);
        public ArrayList<Animais> animais = new ArrayList<>()


        do {
            System.out.println("===== MENU =====");
            System.out.println("1. Adicionar um Círculo;");
            System.out.println("2. Adicionar um Retângulo;");
            System.out.println("3. Calcular média das áreas;");
            System.out.println("4. Calcular média dos perímetros;");
            System.out.println("0. Sair;");
            System.out.println("================");

    } while(opc != 0 )
}